webapp/auth.py
from flask import Blueprint, render_template, redirect, request, url_for, flash
from .models import Users
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask import session
from flask_login import login_user, logout_user, login_required, current_user
auth = Blueprint('auth', __name__)






@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = Users.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash("Logged in successfully", category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.profile', user = current_user))
            else:
                flash("Incorrect password, try again", category='error')
        else:
            flash('Email does not exist', category='error')
    return render_template("login.html", user=current_user)

@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        username = request.form.get('username')
        email = request.form.get('email')
        first_name = request.form.get('first_name')
        last_name = request.form.get('last_name')
        password = request.form.get('password')
        confirm_password = request.form.get('confirm_password')
       

        if len(email) < 4:
            flash("Email must be greater than 3 characters", category='error')
        elif len(first_name) < 2 and len(last_name) < 2:
            flash('First name and last name must be greater than 1 character', category='error')
        elif password != confirm_password:
            flash("Passwords don't match", category='error')
        elif len(password) < 7:
            flash("Password must be at least 7 characters", category='error')
        elif Users.query.filter_by(email=email).first():
            flash("Email already exists", category='error')
        
        else:
            new_user = Users(username=username, first_name=first_name, last_name=last_name, email=email, password=generate_password_hash(password, method='sha256')  )
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash ("Account created!", category='success')
            return redirect (url_for('views.profile'))
    flash ("Ready to Monitor Your Finances? Sign Up to get started", category='success')
    return render_template("sign-up.html", user=current_user)


@auth.route('/logout')
@login_required
def logout():
    session.clear()
    flash("Logged out successfully", category='success')
    logout_user()
    return redirect(url_for('auth.login'))

webapp/views.py
from flask import Blueprint, render_template, redirect, request, url_for, flash
from flask_login import current_user, login_required
from .models import Transactions, Users
from . import db
from datetime import datetime, timedelta
from sqlalchemy import func, desc


views = Blueprint('views', __name__)


@views.route('/all-users')
@login_required
def all_users():
    # Query users
    users = Users.query.all()

    return render_template("users.html", users=users, user=current_user)


@views.route('/', methods=['GET', 'POST'])
@login_required
def home():
    user_id = current_user.id  # Assuming current_user has an 'id' attribute

    transactions = Transactions.query.filter_by(user_id=user_id).all()

    # Query total income and total expenses for the current date
    today = datetime.now().date()
    total_income_today = sum(transaction.amount for transaction in transactions
                             if transaction.transaction_type == 'income'
                             and transaction.transaction_date.date() == today)
    total_expenses_today = sum(
        transaction.amount for transaction in transactions
        if transaction.transaction_type == 'expense'
        and transaction.transaction_date.date() == today)

    seven_days_ago = datetime.now().date() - timedelta(days=7)
    total_income_last_7_days = sum(
        transaction.amount for transaction in transactions
        if transaction.transaction_type == 'income'
        and seven_days_ago <= transaction.transaction_date.date() <= today)
    total_expenses_last_7_days = sum(
        transaction.amount for transaction in transactions
        if transaction.transaction_type == 'expense'
        and seven_days_ago <= transaction.transaction_date.date() <= today)

    #  latest_balance = Transactions.query.filter_by(user_id=user_id).order_by(Transactions.transaction_date.desc()).first()
    #  balance = latest_balance.balance if latest_balance else 0

    total_income = sum(transaction.amount for transaction in transactions
                       if transaction.transaction_type == 'income')
    total_expenses = sum(transaction.amount for transaction in transactions
                         if transaction.transaction_type == 'expense')
    balance = total_income - total_expenses

    if request.method == 'POST':
        description = request.form.get('description')
        transction_type = request.form.get('transaction_type')
        amount = request.form.get('amount')
        date = request.form.get('datetime')
        new_transaction = Transactions(description=description,
                                       transaction_type=transction_type,
                                       date=date,
                                       amount=amount,
                                       user_id=current_user.id)

        if transction_type == 'expense' and float(amount) > balance:
            flash(
                f'your have ₦{balance} left. want to add more funds to yourfundtracker?'
            )
        else:
            db.session.add(new_transaction)
            db.session.commit()
            if transction_type == 'income':
                flash(
                    f'Congratulations {current_user.first_name}!!! ₦{amount} added successfully. Remember your your tracker when you spend from {description}. Good Job.😊',
                    category='success')
            else:
                flash(
                    f'Welldone {current_user.first_name}!!! ₦{amount} was spent for {description}. Keep tracking your expenses. Good Job😊',
                    category='success')

        return redirect(url_for('views.all_transactions'))

    return render_template(
        "dashboard.html",
        user=current_user,
        total_income=total_income,
        total_expenses=total_expenses,
        balance=balance,
        total_expenses_today=total_expenses_today,
        total_income_today=total_income_today,
        total_expenses_last_7_days=total_expenses_last_7_days,
        total_income_last_7_days=total_income_last_7_days)

@views.route('/profile')
@login_required
def profile():
    return render_template("profile.html", user=current_user)


@views.route('/transaction-history')
@login_required
def all_transactions():
    # Query transactions
    user_id = current_user.id  # Assuming current_user has an 'id' attribute

    transactions = Transactions.query.filter_by(
        user_id=user_id).order_by(
        desc(Transactions.date)).all()

    # Calculate total income and total expenses
    global total_income, total_expenses
    total_income = sum(transaction.amount for transaction in transactions
                       if transaction.transaction_type == 'income')
    total_expenses = sum(transaction.amount for transaction in transactions
                         if transaction.transaction_type == 'expense')

    # global total_income, total_expenses
    return render_template('history.html',
                           transactions=transactions,
                           total_income=total_income,
                           total_expenses=total_expenses,
                           user=current_user)


@views.route('/transaction-history/today', methods=['GET'])
@login_required
def transactions_today():
    user_id = current_user.id
    today = datetime.now().date()
    transactions = Transactions.query.filter(
        Transactions.user_id == user_id,
        func.date(Transactions.date) == today
    ).order_by(desc(Transactions.date)).all()
    total_income = sum(transaction.amount for transaction in transactions if transaction.transaction_type == 'income')
    total_expenses = sum(transaction.amount for transaction in transactions if transaction.transaction_type == 'expense')
    return render_template('history.html', transactions=transactions, total_income=total_income, total_expenses=total_expenses, user=current_user)

@views.route('/transaction-history/last-7-days', methods=['GET'])
@login_required
def transactions_last_7_days():
    user_id = current_user.id
    end_date = datetime.now().date()
    start_date = end_date - timedelta(days=6)
    transactions = Transactions.query.filter(
        Transactions.user_id == user_id,
        func.date(Transactions.date).between(start_date, end_date)
    ).order_by(desc(Transactions.date)
    ).all()
    total_income = sum(transaction.amount for transaction in transactions if transaction.transaction_type == 'income')
    total_expenses = sum(transaction.amount for transaction in transactions if transaction.transaction_type == 'expense')
    return render_template('history.html', transactions=transactions, total_income=total_income, total_expenses=total_expenses, user=current_user)

# Select date range
@views.route('/transaction-history/selected-range', methods=['GET'])
@login_required
def transactions_selected_range():
    user_id = current_user.id
    start_date = request.args.get('start_date')
    end_date = request.args.get('end_date')

    # Parse dates into datetime objects if provided
    if start_date:
        start_date = datetime.strptime(start_date, '%Y-%m-%d').date()
    else:
        # Set a default start date if it's empty
        start_date = datetime.min.date()

    if end_date:
        end_date = datetime.strptime(end_date, '%Y-%m-%d').date()
    else:
        end_date = datetime.max.date()

    # Ensure that the date range is valid
    user_registration_date = Users.query.filter_by(id=user_id).first().date_joined.date()

    if start_date < user_registration_date:
        start_date = user_registration_date

    if end_date < start_date:
        end_date = start_date

    transactions = Transactions.query.filter(
        Transactions.user_id == user_id,
        func.date(Transactions.date).between(start_date, end_date)
    ).all()

    # Calculate total income and total expenses for the date range
    # total_income = sum(transaction.amount for transaction in transactions if transaction.transaction_type == 'income')
    # total_expenses = sum(transaction.amount for transaction in transactions if transaction.transaction_type == 'expense')
    total_income = sum(transaction.amount for transaction in transactions if transaction.transaction_type == 'income')
    total_expenses = sum(transaction.amount for transaction in transactions if transaction.transaction_type == 'expense')

    return render_template('history.html', transactions=transactions, total_income=total_income, total_expenses=total_expenses, user=current_user)


@views.route('/edit/<int:transaction_id>', methods=['GET', 'POST'])
@login_required
def edit_transaction(transaction_id):

    user=current_user
    # Fetch the transaction by ID from the database
    transaction = Transactions.query.get(transaction_id)

    if not transaction:
        flash('Transaction not found', category='error')
        return redirect(url_for('views.all_transaction'))

    if request.method == 'POST':
        # Handle the form submission to update the transaction
        # Update the transaction fields based on the form data
        transaction.description = request.form.get('description')
        transaction.transaction_type = request.form.get('transaction_type')
        transaction.amount = request.form.get('amount')
        transaction.date = request.form.get('datetime')


        # Commit the changes to the database
        db.session.commit()

        flash('Transaction updated successfully!', category='success')
        return redirect(url_for('views.all_transactions'))

    # Render the edit form with the transaction data
    return render_template('edit.html', transaction=transaction, user=user)

@views.route('/delete/<int:transaction_id>', methods=['POST'])
@login_required
def delete_transaction(transaction_id):
    user=current_user
    # Fetch the transaction by ID from the database
    transaction = Transactions.query.get(transaction_id)

    if not transaction:
        flash('Transaction not found', category='error')

webapp/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
        integrity="sha384-eudr/iUqCIEHjYaeJQQJ83Fz9ppss56FJd5JqI01vNM2Ubc8NVggg1qsFEcPKs7U3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        crossorigin="anonymous" />

    <title>{% block title %}Page Title{% endblock %}</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar">
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" id="home" href="/">Dashboard</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="transaction_history" href="/transaction-history">History</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="profile" href="/profile">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="logout" href="/logout">Logout</a>
                </li>
               
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" id="login" href="/login">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="signUp" href="/sign-up">Sign Up</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                {% if category == 'error' %}
                <div class="alert alert-danger  alert-dismissible fade show" role="alert">
                    {{message}}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% else %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    {{message}}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    {% endwith %}

    <div class="container">
        {% block content %}

        {% endblock %}
    </div>

 

    <!-- Footer -->
    <footer class="mt-5">
            <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
                integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
                crossorigin="anonymous"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
                integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
                crossorigin="anonymous"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
                integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
                crossorigin="anonymous"></script>
            <script type="text/javascript" src="{{ url_for('static', filename='index.js') }}"></script>
            <div class="container text-center">

            <p>&copy; 2023 FinTracker. All rights reserved. | <a href="/privacy">Privacy Policy</a></p>
            <p>This is a beta version.</p>
        </div>
    </footer>
</body>

</html>

webapp/templates/dashboard.html
{% extends "base.html" %}

{% block title %}Dashboard - FinTracker{% endblock %}

{% block content %}
<div class="jumbotron mt-4 ">
    <h1 class="display-4"><i class="fa fa-line-chart"></i> Welcome to FinTracker Dashboard!</h1>
    <p class="lead">Start by inputting the amount you want to track and keep your finances in check.</p>
</div>

<div class="row mt-5">
    <div class="col-md-4">
        <div class="card text-center">
            <div class="card-body">
                <h5 class="card-title"><i class="fa fa-money"></i> Total Funds Registered</h5>
                <p class="card-text">₦ {{ total_income }}</p>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card text-center">
            <div class="card-body">
                <h5 class="card-title"> <a href="/transaction-history"> <i class="fa fa-shopping-cart"></i> Total Expenses Tracked</a></h5>
                <p class="card-text">₦ {{ total_expenses }}</p>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card text-center">
            <div class="card-body">
                <h5 class="card-title"><i class="fa fa-balance-scale"></i> Balance Left</h5>
                <p class="card-text">₦ {{ balance }}</p>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card text-center">
            <div class="card-body">
                <h5 class="card-title"><a  href="/transaction-history/today"><i class="fa fa-shopping-cart"></i> Today Expenses Tracked</a></h5>
                <p class="card-text">₦ {{ total_expenses_today }}</p>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card text-center">
            <div class="card-body">
                <h5 class="card-title"><a href="/transaction-history/last-7-days"><i class="fa fa-shopping-cart"></i> &nbsp; 1 Week Expenses</a> </h5>
                <p class="card-text">₦ {{ total_expenses_last_7_days }}</p>
            </div>
        </div>
    </div>
</div>

<div class="jumbotron mt-4 mt-4 border border-primary">
    <!-- Tab forms here -->
    <h3 style="text-align: center;">Track Your Funds Here</h3>
    <div class="row mt-lg-5">
        <div class="col-md-12">
            <ul class="nav nav-tabs" id="myTabs">
                <li class="nav-item">
                    <a class="nav-link" id="income-tab" data-toggle="tab" href="#income-form">Add Fund For
                        Tracking</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" id="expense-tab" data-toggle="tab" href="#expense-form">Track Expenses</a>
                </li>
            </ul>
            <div class="tab-content mt-4">
                <!-- income Form -->
                <div class="tab-pane fade" id="income-form">
                    <form method="POST" action="{{ url_for('views.home') }}">
                        <!-- Add income form fields here -->
                        <input type="hidden" name="transaction_type" value="income">
                        <!-- Set the transaction type to 'income' -->
                        <div class="form-group">
                            <label for="income-description">Description</label>
                            <input type="text" class="form-control" id="income-description" name="description" required>
                        </div>
                        <div class="form-group">
                            <label for="income-amount">Amount</label>
                            <input type="number" class="form-control" id="income-amount" name="amount" step="0.01" required>
                        </div>
                        <div class="form-group">
                            <label for="income-datetime">Date and Time</label>
                            <input type="datetime-local" class="form-control" id="income-datetime" name="datetime" value=""
                                required>
                        </div>
                        <button type="submit" class="btn btn-primary">Add fund</button>
                    </form>
                </div>
    
                <!-- Expense Form -->
                <div class="tab-pane fade show active" id="expense-form">
                    <form method="POST" action="{{ url_for('views.home') }}">
                        <!-- Add expense form fields here -->
                        <input type="hidden" name="transaction_type" value="expense">
                        <!-- Set the transaction type to 'expense' -->
                        <div class="form-group">
                            <label for="expense-amount">Amount</label>
                            <input type="number" class="form-control" id="expense-amount" name="amount" step="0.01"
                                required>
                        </div>
                        <div class="form-group">
                            <label for="expense-description">What for?</label>
                            <input type="text" class="form-control" id="expense-description" name="description" required>
                        </div>
                        <div class="form-group">
                            <label for="expense-datetime">Date and Time</label>
                            <input type="datetime-local" class="form-control" id="expense-datetime" name="datetime" value=""
                                required>
                        </div>
                        <button type="submit" class="btn btn-primary">Add Expense</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>



<script>
    $(document).ready(function () {
        $('#myTabs a').click(function (e) {
            e.preventDefault()
            $(this).tab('show')
        });
    });

    // Set the default value of the datetime input fields to the current date and time
    const currentDatetime = new Date().toISOString().slice(0, 16);
    document.getElementById('income-datetime').value = currentDatetime;
    document.getElementById('expense-datetime').value = currentDatetime;

    // Set the default value to be faded until the user selects a date
        const setInitialColor = function (elementId) {
            const element = document.getElementById(elementId);
            element.style.color = element.value ? 'black' : 'grey';
        };

        setInitialColor('income-datetime');
        setInitialColor('expense-datetime');

    

    // Set the default value to be faded until the user selects a date
    document.getElementById('income-datetime').addEventListener('input', function () {
        this.style.color = this.value ? 'black' : 'grey';
    });

    document.getElementById('expense-datetime').addEventListener('input', function () {
        this.style.color = this.value ? 'black' : 'grey';
    });
</script>

{% endblock %}

webapp/templates/edit.html
{% extends "base.html" %}

{% block title %}Edit Transaction - FinTracker{% endblock %}

{% block content %}
<div class="jumbotron mt-4 mt-4 border border-primary">
    <h1 class="display-4"><i class="fa fa-pencil"></i> Edit Transaction</h1>
</div>

<div class="row mt-3">
    <div class="col-10 offset-1">
        <form method="POST">
            <div class="form-group">
                <label for="description">Description:</label>
                <input type="text" class="form-control" id="description" name="description"
                    value="{{ transaction.description }}" required>
            </div>
            <div class="form-group">
                <label for="transaction_type">Transaction Type:</label>
                <select class="form-control" id="transaction_type" name="transaction_type" required>
                    <option value="income" {% if transaction.transaction_type=='income' %}selected{% endif %}>Income
                    </option>
                    <option value="expense" {% if transaction.transaction_type=='expense' %}selected{% endif %}>Expense
                    </option>
                </select>
            </div>
            <div class="form-group">
                <label for="amount">Amount:</label>
                <input type="number" class="form-control" id="amount" name="amount" step="0.01"
                    value="{{ transaction.amount }}" required>
            </div>
            <div class="form-group">
                <label for="expense-datetime">Date and Time</label>
                <input type="datetime-local" class="form-control" id="expense-datetime" name="datetime" value="{{ transaction.date }}" required>
            </div>
            <button type="submit" class="btn btn-primary">Update Transaction</button>
        </form>
    </div>
</div>
{% endblock %}

webapp/templates/history.html
{% extends "base.html" %}

{% block title %}Transaction History - FinTracker{% endblock %}

{% block content %}
<div class="jumbotron mt-4">
    <h1 class="display-4"><i class="fa fa-history"></i> Transaction History</h1>
    <div class="transaction-summary mt-3">
        <h4>Total Income: ₦{{ total_income }}</h4>
        <h4>Total Expenses: ₦{{ total_expenses }}</h4>
    </div>
</div>

<div class="row mt-3">
    <div class="col-12">
        <!-- Date Filter Form -->
        <form method="GET" action="{{ url_for('views.transactions_selected_range') }}">
            <div class="form-group">
                <label for="start_date">Start Date:</label>
                <input type="date" class="form-control" id="start_date" name="start_date">
            </div>
            <div class="form-group">
                <label for="end_date">End Date:</label>
                <input type="date" class="form-control" id="end_date" name="end_date">
            </div>
            <button type="submit" class="btn btn-primary">Filter</button><br><br>
            <a class="btn btn-primary mr-2 mt-2" href="/transaction-history">All Transactions</a>
            <a class="btn btn-primary mr-2 mt-2" href="/transaction-history/today">Todays Transactions</a>
            <a class="btn btn-primary mr-2 mt-2" href="/transaction-history/last-7-days">7 days history</a>
            <a class="btn btn-success mr-2 mt-2" href="/#expense-form">Add Transaction</a>
        </form>
        <!-- Add this button or link where you want to trigger the history clearing -->
        <form method="POST" action="{{ url_for('views.clear_history') }}"
            onsubmit="return confirm('Are you sure you want to clear all transaction history?');">
            <button type="submit" class="btn btn-danger mt-2">Clear Transaction History</button>
        </form>

        {% if transactions %}
        <div class="table-responsive">
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Transaction ID</th>
                        <th>Date</th>
                        <th>Description</th>
                        <th>Income</th>
                        <th>Expense</th>
                        <th>Balance</th>
                        <th>Edit</th>
                        <th>Delete</th>
                    </tr>
                </thead>
                <tbody>
                    {% for transaction in transactions %}
                    <tr>
                        <td>{{ transaction.transaction_id }}</td>
                        <td>{{ transaction.date }}</td>
                        <td>{{ transaction.description }}</td>
                        <td>{% if transaction.transaction_type == 'income' %}₦{{ transaction.amount }}{% endif %}</td>
                        <td>{% if transaction.transaction_type == 'expense' %}₦{{ transaction.amount }}{% endif %}</td>
                        <td>₦{{ transaction.balance }}</td>
                        <td>
                            <a href="{{ url_for('views.edit_transaction', transaction_id=transaction.transaction_id) }}"
                                class="btn btn-warning btn-sm">
                                <i class="fas fa-pencil-alt"></i> Edit
                            </a>
                        </td>
                        <td>
                            <!-- Update the delete button to use a form with POST method -->
                            <form method="POST"
                                action="{{ url_for('views.delete_transaction', transaction_id=transaction.transaction_id) }}"
                                onsubmit="return confirm('Are you sure you want to delete this transaction?');">
                                <button type="submit" class="btn btn-danger btn-sm">
                                    <i class="fas fa-trash-alt"></i> Delete
                                </button>
                            </form>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% else %}
        <p>No transactions</p>
        {% endif %}
    </div>
</div>
{% endblock %}

webapp/templates/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="row mt-4">
    <div class="col-md-6 offset-md-3">
        <h2>Login</h2>
    <form method="POST">
        <div class="form-group">
            <label for="email">Email Address</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="Enter email">
        </div>
    
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" id="password" name="password" placeholder="Enter Password">
        </div>
    
    
        <br>
        <button type="submit" class="btn btn-primary btn-sm">Login</button>
        <a class="btn btn-primary btn-sm" href="{{ url_for('auth.sign_up') }}">Sign Up</a>
    </form>
</div>
{% endblock %}